import { type FormEvent, type ReactNode, useCallback, useEffect, useState } from 'react'
import { api, ApiError, type Charger, type ChargerInput, type SimulationStatus, type Station, type StationInput, type SystemConfiguration, type SystemConfigurationInput, type Tariff, type TariffInput } from '../api/client'
import { useAuth } from '../auth/context'
import { AppShell } from '../layouts/AppShell'

type Notice = { kind: 'success' | 'error'; text: string } | null
const stationBlank: StationInput = { name: '', description: null, grid_limit_kw: 60, station_peak_solar_kw: 0, is_active: true }
const chargerBlank: ChargerInput = { station_id: '', name: '', code: '', max_power_kw: 22, status: 'AVAILABLE', is_active: true }
const tariffBlank = (): TariffInput => ({ name: '', price_per_kwh: 0.92, currency: 'BRL', is_active: true, valid_from: new Date().toISOString().slice(0, 16), valid_until: null })
const configurationBlank: SystemConfigurationInput = { simulation_speed: 60, grid_emission_factor_kg_per_kwh: 0.084, high_demand_threshold: 0.85, high_solar_availability_threshold: 0.8, medium_peak_threshold: 0.7, high_peak_threshold: 0.9 }

function message(error: unknown) {
  if (!(error instanceof ApiError)) return 'Não foi possível concluir a operação.'
  if (error.status === 409) return `Conflito: ${error.message}`
  if (error.status === 422) return `Revise os campos: ${error.message}`
  return error.message
}

function Section({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <section className="admin-section" aria-labelledby={`section-${title}`}><div className="section-heading"><div><h2 id={`section-${title}`}>{title}</h2><p>{description}</p></div></div>{children}</section>
}

function Feedback({ notice }: { notice: Notice }) {
  if (!notice) return null
  return <p role={notice.kind === 'error' ? 'alert' : 'status'} className={`operation-notice operation-notice--${notice.kind}`}>{notice.text}</p>
}

function StationForm({ initial = stationBlank, label, onSave }: { initial?: StationInput; label: string; onSave: (value: StationInput) => Promise<boolean | void> }) {
  const [value, setValue] = useState(initial); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<Notice>(null)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setNotice(null); try { const saved = await onSave({ ...value, description: value.description || null }); if (saved !== false) setNotice({ kind: 'success', text: 'Estação salva.' }) } catch (error) { setNotice({ kind: 'error', text: message(error) }) } finally { setBusy(false) } }
  return <form className="admin-form" onSubmit={submit}><div className="form-grid"><label>Nome<input required maxLength={120} value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} /></label><label>Limite da rede (kW)<input required type="number" min="0.01" step="0.01" value={value.grid_limit_kw} onChange={e => setValue({ ...value, grid_limit_kw: e.target.valueAsNumber })} /></label><label>Pico solar (kW)<input required type="number" min="0" step="0.01" value={value.station_peak_solar_kw} onChange={e => setValue({ ...value, station_peak_solar_kw: e.target.valueAsNumber })} /></label><label className="check-field"><input type="checkbox" checked={value.is_active} onChange={e => setValue({ ...value, is_active: e.target.checked })} /> Estação ativa</label><label className="wide-field">Descrição<textarea maxLength={2000} value={value.description ?? ''} onChange={e => setValue({ ...value, description: e.target.value })} /></label></div><Feedback notice={notice} /><button disabled={busy}>{busy ? 'Salvando...' : label}</button></form>
}

function ChargerForm({ stations, initial = chargerBlank, label, onSave }: { stations: Station[]; initial?: ChargerInput; label: string; onSave: (value: ChargerInput) => Promise<boolean | void> }) {
  const [value, setValue] = useState({ ...initial, station_id: initial.station_id || stations[0]?.id || '' }); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<Notice>(null)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setNotice(null); try { const saved = await onSave(value); if (saved !== false) setNotice({ kind: 'success', text: 'Carregador salvo.' }) } catch (error) { setNotice({ kind: 'error', text: message(error) }) } finally { setBusy(false) } }
  return <form className="admin-form" onSubmit={submit}><div className="form-grid"><label>Estação<select required value={value.station_id} onChange={e => setValue({ ...value, station_id: e.target.value })}><option value="">Selecione</option>{stations.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Nome<input required maxLength={120} value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} /></label><label>Código<input required maxLength={60} value={value.code} onChange={e => setValue({ ...value, code: e.target.value })} /></label><label>Potência máxima (kW)<input required type="number" min="0.01" step="0.01" value={value.max_power_kw} onChange={e => setValue({ ...value, max_power_kw: e.target.valueAsNumber })} /></label><label>Status<select value={value.status} onChange={e => setValue({ ...value, status: e.target.value as Charger['status'] })}><option value="AVAILABLE">Disponível</option><option value="CHARGING">Carregando</option><option value="UNAVAILABLE">Indisponível</option></select></label><label className="check-field"><input type="checkbox" checked={value.is_active} onChange={e => setValue({ ...value, is_active: e.target.checked })} /> Carregador ativo</label></div><Feedback notice={notice} /><button disabled={busy || !stations.length}>{busy ? 'Salvando...' : label}</button></form>
}

function TariffForm({ initial = tariffBlank(), label, onSave }: { initial?: TariffInput; label: string; onSave: (value: TariffInput) => Promise<void> }) {
  const [value, setValue] = useState(initial); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<Notice>(null)
  async function submit(event: FormEvent) { event.preventDefault(); if (value.is_active && !window.confirm('Ativar esta tarifa desativará a tarifa ativa atual. Continuar?')) return; setBusy(true); setNotice(null); try { await onSave({ ...value, valid_from: new Date(value.valid_from).toISOString(), valid_until: value.valid_until ? new Date(value.valid_until).toISOString() : null }); setNotice({ kind: 'success', text: 'Tarifa salva.' }) } catch (error) { setNotice({ kind: 'error', text: message(error) }) } finally { setBusy(false) } }
  return <form className="admin-form" onSubmit={submit}><div className="form-grid"><label>Nome<input required maxLength={120} value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} /></label><label>Preço por kWh<input required type="number" min="0" step="0.0001" value={value.price_per_kwh} onChange={e => setValue({ ...value, price_per_kwh: e.target.valueAsNumber })} /></label><label>Moeda<input required minLength={3} maxLength={3} value={value.currency} onChange={e => setValue({ ...value, currency: e.target.value.toUpperCase() })} /></label><label>Válida desde<input required type="datetime-local" value={value.valid_from.slice(0, 16)} onChange={e => setValue({ ...value, valid_from: e.target.value })} /></label><label>Válida até<input type="datetime-local" value={value.valid_until?.slice(0, 16) ?? ''} onChange={e => setValue({ ...value, valid_until: e.target.value || null })} /></label><label className="check-field"><input type="checkbox" checked={value.is_active} onChange={e => setValue({ ...value, is_active: e.target.checked })} /> Tarifa ativa</label></div><Feedback notice={notice} /><button disabled={busy}>{busy ? 'Salvando...' : label}</button></form>
}

function ConfigurationForm({ initial, exists, onSaved }: { initial: SystemConfigurationInput; exists: boolean; onSaved: (value: SystemConfiguration) => void }) {
  const [value, setValue] = useState(initial); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<Notice>(null)
  const number = (field: keyof SystemConfigurationInput, next: number) => setValue({ ...value, [field]: next })
  async function submit(event: FormEvent) { event.preventDefault(); if (value.medium_peak_threshold >= value.high_peak_threshold) { setNotice({ kind: 'error', text: 'O limiar médio deve ser menor que o limiar alto.' }); return } setBusy(true); setNotice(null); try { const saved = exists ? await api.updateSystemConfiguration(value) : await api.createSystemConfiguration(value); onSaved(saved); setNotice({ kind: 'success', text: 'Parâmetros salvos.' }) } catch (error) { setNotice({ kind: 'error', text: message(error) }) } finally { setBusy(false) } }
  return <form className="admin-form" onSubmit={submit}><div className="form-grid"><label>Velocidade da simulação<input required type="number" min="1" step="1" value={value.simulation_speed} onChange={e => number('simulation_speed', e.target.valueAsNumber)} /></label><label>Fator de emissão (kg/kWh)<input required type="number" min="0" step="0.001" value={value.grid_emission_factor_kg_per_kwh} onChange={e => number('grid_emission_factor_kg_per_kwh', e.target.valueAsNumber)} /></label><label>Limiar de demanda alta<input required type="number" min="0.01" max="1" step="0.01" value={value.high_demand_threshold} onChange={e => number('high_demand_threshold', e.target.valueAsNumber)} /></label><label>Limiar de disponibilidade solar alta<input required type="number" min="0.01" max="1" step="0.01" value={value.high_solar_availability_threshold} onChange={e => number('high_solar_availability_threshold', e.target.valueAsNumber)} /></label><label>Limiar de risco médio<input required type="number" min="0.01" max="0.99" step="0.01" value={value.medium_peak_threshold} onChange={e => number('medium_peak_threshold', e.target.valueAsNumber)} /></label><label>Limiar de risco alto<input required type="number" min="0.01" max="1" step="0.01" value={value.high_peak_threshold} onChange={e => number('high_peak_threshold', e.target.valueAsNumber)} /></label></div><p className="field-help">Valores de limiar são proporções entre 0 e 1. O alerta solar compara a geração disponível ao pico solar da estação; a classificação de risco permanece calculada pelo backend.</p><Feedback notice={notice} /><button disabled={busy}>{busy ? 'Salvando...' : exists ? 'Atualizar parâmetros' : 'Criar parâmetros'}</button></form>
}

export function AdminOperationsPage() {
  const { logout } = useAuth(); const [stations, setStations] = useState<Station[]>([]); const [chargers, setChargers] = useState<Charger[]>([]); const [tariffs, setTariffs] = useState<Tariff[]>([]); const [configuration, setConfiguration] = useState<SystemConfiguration | null>(null); const [simulation, setSimulation] = useState<SimulationStatus | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [simNotice, setSimNotice] = useState<Notice>(null); const [attempt, setAttempt] = useState(0)
  const load = useCallback(async () => { setLoading(true); setLoadError(''); try { const [s, c, t, configResult, sim] = await Promise.all([api.stations(), api.chargers(), api.tariffs(), api.systemConfiguration().catch(error => error instanceof ApiError && error.status === 404 ? null : Promise.reject(error)), api.simulationStatus()]); setStations(s); setChargers(c); setTariffs(t); setConfiguration(configResult); setSimulation(sim) } catch { setLoadError('Não foi possível carregar a administração.') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load, attempt])
  async function simulationAction(action: 'start' | 'stop' | 'reset') { if (action === 'reset' && !window.confirm('Redefinir o relógio da simulação? Os registros persistidos não serão apagados.')) return; setSimNotice(null); try { const result = action === 'start' ? await api.startSimulation() : action === 'stop' ? await api.stopSimulation() : await api.resetSimulation(); setSimulation(result); setSimNotice({ kind: 'success', text: `Simulação ${action === 'start' ? 'iniciada' : action === 'stop' ? 'parada' : 'redefinida'}.` }) } catch (error) { setSimNotice({ kind: 'error', text: message(error) }) } }
  const refresh = async () => { await load(); setEditing(null) }
  return <AppShell><div className="dashboard admin-operations"><header className="dashboard-heading"><div><p className="eyebrow">Administração</p><h1>Operação do MVP</h1><p>Infraestrutura, tarifas e parâmetros operacionais.</p></div><button onClick={logout}>Sair</button></header>{loadError ? <div role="alert" className="dashboard-error"><p>{loadError}</p><button onClick={() => setAttempt(x => x + 1)}>Tentar novamente</button></div> : loading ? <p role="status">Carregando configurações...</p> : <>
    <Section title="Estações" description="Cadastre instalações e ajuste seus limites energéticos."><StationForm label="Cadastrar estação" onSave={async value => { await api.createStation(value); await refresh() }} /><div className="admin-list">{stations.map(item => <article key={item.id}><div><strong>{item.name}</strong><span>{item.grid_limit_kw} kW de rede · {item.station_peak_solar_kw} kW solar · {item.is_active ? 'Ativa' : 'Inativa'}</span></div><button className="secondary-button" onClick={() => setEditing(editing === `station-${item.id}` ? null : `station-${item.id}`)}>Editar</button>{editing === `station-${item.id}` && <StationForm label="Salvar estação" initial={{ name: item.name, description: item.description, grid_limit_kw: item.grid_limit_kw, station_peak_solar_kw: item.station_peak_solar_kw, is_active: item.is_active }} onSave={async value => { if (value.is_active !== item.is_active && !window.confirm('Alterar a disponibilidade desta estação pode afetar a operação. Continuar?')) return false; await api.updateStation(item.id, value); await refresh() }} />}</article>)}</div></Section>
    <Section title="Carregadores" description="Associe equipamentos às estações e controle disponibilidade."><ChargerForm stations={stations} label="Cadastrar carregador" onSave={async value => { await api.createCharger(value); await refresh() }} />{!stations.length && <p role="status">Cadastre uma estação antes do primeiro carregador.</p>}<div className="admin-list">{chargers.map(item => <article key={item.id}><div><strong>{item.name} ({item.code})</strong><span>{item.max_power_kw} kW · {item.status} · {item.is_active ? 'Ativo' : 'Inativo'}</span></div><button className="secondary-button" onClick={() => setEditing(editing === `charger-${item.id}` ? null : `charger-${item.id}`)}>Editar</button>{editing === `charger-${item.id}` && <ChargerForm stations={stations} label="Salvar carregador" initial={{ station_id: item.station_id, name: item.name, code: item.code, max_power_kw: item.max_power_kw, status: item.status, is_active: item.is_active }} onSave={async value => { if ((value.status !== item.status || value.is_active !== item.is_active) && !window.confirm('Alterar o estado do carregador pode afetar sessões. Continuar?')) return false; await api.updateCharger(item.id, value); await refresh() }} />}</article>)}</div></Section>
    <Section title="Tarifas" description="Gerencie valores e vigências; apenas uma tarifa fica ativa."><TariffForm label="Cadastrar tarifa" onSave={async value => { await api.createTariff(value); await refresh() }} /><div className="admin-list">{tariffs.map(item => <article key={item.id}><div><strong>{item.name}</strong><span>{item.currency} {item.price_per_kwh}/kWh · {item.is_active ? 'Ativa' : 'Inativa'}</span></div><button className="secondary-button" onClick={() => setEditing(editing === `tariff-${item.id}` ? null : `tariff-${item.id}`)}>Editar</button>{editing === `tariff-${item.id}` && <TariffForm label="Salvar tarifa" initial={{ name: item.name, price_per_kwh: Number(item.price_per_kwh), currency: item.currency, is_active: item.is_active, valid_from: item.valid_from, valid_until: item.valid_until }} onSave={async value => { await api.updateTariff(item.id, value); await refresh() }} />}</article>)}</div></Section>
    <Section title="Energia, risco e simulação" description="Configure parâmetros usados pelos serviços determinísticos e preditivos."><ConfigurationForm key={configuration?.updated_at ?? 'new'} exists={Boolean(configuration)} initial={configuration ? { simulation_speed: configuration.simulation_speed, grid_emission_factor_kg_per_kwh: configuration.grid_emission_factor_kg_per_kwh, high_demand_threshold: configuration.high_demand_threshold, high_solar_availability_threshold: configuration.high_solar_availability_threshold, medium_peak_threshold: configuration.medium_peak_threshold, high_peak_threshold: configuration.high_peak_threshold } : configurationBlank} onSaved={setConfiguration} /><div className="simulation-control"><h3>Controle da simulação</h3><p role="status">Estado: <strong>{simulation?.state === 'RUNNING' ? 'Em execução' : 'Parada'}</strong></p><div className="row-actions"><button disabled={simulation?.state === 'RUNNING'} onClick={() => void simulationAction('start')}>Iniciar</button><button className="secondary-button" disabled={simulation?.state === 'STOPPED'} onClick={() => void simulationAction('stop')}>Parar</button><button className="danger-button" disabled={simulation?.state !== 'STOPPED'} onClick={() => void simulationAction('reset')}>Redefinir relógio</button></div><Feedback notice={simNotice} /></div></Section>
  </>}</div></AppShell>
}
